services:
  - type: web
    name: video-chat-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: STEAM_API_KEY
        sync: false
      - key: STEAM_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://video-chat-app.onrender.com
